/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.linz.objectrenderer;

import Sirius.navigator.connection.SessionManager;
import Sirius.navigator.exception.ConnectionException;

import Sirius.server.middleware.types.MetaClass;
import Sirius.server.middleware.types.MetaObject;

import at.ac.ait.enviro.tsapi.timeseries.TimeSeries;
import at.ac.ait.enviro.tsapi.timeseries.TimeStamp;

import org.apache.commons.httpclient.Credentials;
import org.apache.log4j.Logger;

import org.openide.awt.Mnemonics;
import org.openide.util.NbBundle;

import java.awt.CardLayout;
import java.awt.EventQueue;

import java.io.IOException;

import java.util.concurrent.Future;

import javax.swing.JComponent;
import javax.swing.table.AbstractTableModel;

import de.cismet.cids.custom.sudplan.AbstractCidsBeanRenderer;
import de.cismet.cids.custom.sudplan.TimeSeriesRemoteHelper;
import de.cismet.cids.custom.sudplan.TimeseriesRetriever;
import de.cismet.cids.custom.sudplan.TimeseriesRetrieverConfig;
import de.cismet.cids.custom.sudplan.commons.SudplanConcurrency;
import de.cismet.cids.custom.sudplan.converter.TimeseriesConverter;
import de.cismet.cids.custom.sudplan.data.io.TimeSeriesExportWizardAction;
import de.cismet.cids.custom.sudplan.linz.LinzTimeSeriesExportWizardAction;
import de.cismet.cids.custom.sudplan.linz.SwmmInput;
import de.cismet.cids.custom.sudplan.linz.converter.LinzNetcdfConverter;
import de.cismet.cids.custom.sudplan.linz.wizard.SwmmPlusEtaWizardAction;

import de.cismet.cids.dynamics.CidsBean;

import de.cismet.cids.navigator.utils.ClassCacheMultiple;

import de.cismet.tools.gui.TitleComponentProvider;

/**
 * DOCUMENT ME!
 *
 * @author   p-a-s-c-a-l
 * @version  $Revision$, $Date$
 */
public class LinzSensorRenderer extends AbstractCidsBeanRenderer implements TitleComponentProvider {

    //~ Static fields/initializers ---------------------------------------------

    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(LinzSensorRenderer.class);
    public static final String NETCDF_HOST = TimeSeriesRemoteHelper.NETCDF_HOST;
    public static final Credentials NETCDF_CREDS = TimeSeriesRemoteHelper.NETCDF_CREDS;
    public static final String LINZ_STATION_HYE = "LI-HYE";
    public static final String LINZ_STATION_WIE = "LI-WIE";
    public static final String LINZ_STATION_WOE = "LI-WOE";
    public static final String LINZ_STATION_PCE = "LI-PCE";

    //~ Instance fields --------------------------------------------------------

    private final transient TimeSeriesExportWizardAction exportAction = new LinzTimeSeriesExportWizardAction();

    private final transient LinzSensorTitleComponent linzSensorTitleComponent = new LinzSensorTitleComponent();
    private transient String currentSensorType;
    private transient EventDetectionUpdater eventDetectionUpdater = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel eventDetectionPanel;
    private javax.swing.JButton exportButton;
    private javax.swing.JScrollPane jScrollPaneEventDetection;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JTable tblEventDetection;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form LinzWwtpRenderer.
     */
    public LinzSensorRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        eventDetectionPanel = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        jScrollPaneEventDetection = new javax.swing.JScrollPane();
        tblEventDetection = new javax.swing.JTable();
        progressPanel = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        progressLabel = new javax.swing.JLabel();
        exportButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        eventDetectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
                org.openide.util.NbBundle.getMessage(
                    LinzSensorRenderer.class,
                    "LinzSensorRenderer.eventDetectionPanel.border.title"))); // NOI18N
        eventDetectionPanel.setOpaque(false);
        eventDetectionPanel.setLayout(new java.awt.GridBagLayout());

        cardPanel.setOpaque(false);
        cardPanel.setLayout(new java.awt.CardLayout());

        tblEventDetection.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {}));
        jScrollPaneEventDetection.setViewportView(tblEventDetection);

        cardPanel.add(jScrollPaneEventDetection, "events");

        progressPanel.setOpaque(false);
        progressPanel.setLayout(new java.awt.GridBagLayout());

        progressBar.setIndeterminate(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        progressPanel.add(progressBar, gridBagConstraints);

        progressLabel.setText(org.openide.util.NbBundle.getMessage(
                LinzSensorRenderer.class,
                "LinzSensorRenderer.progressLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        progressPanel.add(progressLabel, gridBagConstraints);

        cardPanel.add(progressPanel, "progress");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        eventDetectionPanel.add(cardPanel, gridBagConstraints);

        exportButton.setAction(exportAction);
        exportButton.setText(org.openide.util.NbBundle.getMessage(
                LinzSensorRenderer.class,
                "LinzSensorRenderer.exportButton.text")); // NOI18N
        exportButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        eventDetectionPanel.add(exportButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(eventDetectionPanel, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    @Override
    public void setTitle(final String title) {
        super.setTitle(title);
        this.linzSensorTitleComponent.setTitle(title);
    }

    @Override
    public JComponent getTitleComponent() {
        return linzSensorTitleComponent;
    }

    @Override
    protected void init() {
        try {
            assert this.getCidsBean() != null : "Sensor Bean must not be null!";

            final String sensorType = this.getCidsBean().getProperty("type").toString();
            if (LOG.isDebugEnabled()) {
                LOG.debug("loading event for sensor '" + sensorType + "'");
            }
            if (LINZ_STATION_HYE.indexOf(sensorType) != -1) {
                currentSensorType = LINZ_STATION_HYE;
            } else if (LINZ_STATION_WIE.indexOf(sensorType) != -1) {
                currentSensorType = LINZ_STATION_WIE;
            } else if (LINZ_STATION_WOE.indexOf(sensorType) != -1) {
                currentSensorType = LINZ_STATION_WOE;
            } else if (LINZ_STATION_PCE.indexOf(sensorType) != -1) {
                currentSensorType = LINZ_STATION_PCE;
            } else {
                throw new Exception("Unsupported Sensor Type '" + sensorType
                            + "', expected '"
                            + LINZ_STATION_HYE + "', '"
                            + LINZ_STATION_WIE + "', '"
                            + LINZ_STATION_WOE + "' or '"
                            + LINZ_STATION_PCE + "'");
            }

            if ((eventDetectionUpdater != null) && eventDetectionUpdater.isRunning()) {
                LOG.warn("An Event Detection update thread is still running");
                // eventDetectionUpdater.stopIt();
            } else {
                Mnemonics.setLocalizedText(
                    progressLabel,
                    NbBundle.getMessage(
                        LinzSensorRenderer.class,
                        "LinzSensorRenderer.progressLabel.text")); // NOI18N
                progressBar.setIndeterminate(true);
                ((CardLayout)cardPanel.getLayout()).show(cardPanel, "progress");

                eventDetectionUpdater = new EventDetectionUpdater(currentSensorType);
                SudplanConcurrency.getSudplanGeneralPurposePool().execute(eventDetectionUpdater);
            }
        } catch (Exception e) {
            LOG.error(e.getMessage(), e);
            progressBar.setIndeterminate(false);
            org.openide.awt.Mnemonics.setLocalizedText(
                progressLabel,
                org.openide.util.NbBundle.getMessage(
                    LinzSensorRenderer.class,
                    "LinzSensorRenderer.progressLabel.error")); // NOI18N
            ((CardLayout)cardPanel.getLayout()).show(cardPanel, "progress");
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @param   sensor  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     *
     * @throws  IOException  DOCUMENT ME!
     */
    private MetaObject[] getTimeseriesBeans(final String sensor) throws IOException {
        final String domain = SessionManager.getSession().getUser().getDomain();
        final MetaClass mc = ClassCacheMultiple.getMetaClass(domain, SwmmPlusEtaWizardAction.TABLENAME_TIMESERIES);
        if (LOG.isDebugEnabled()) {
            LOG.debug("retrieving event timeseries (" + SwmmPlusEtaWizardAction.TABLENAME_TIMESERIES
                        + ")for sensor '" + sensor + "' from domain '" + domain + "'");
        }

        if (mc == null) {
            throw new IOException("cannot find TIMESERIES metaclass"); // NOI18N
        }

        final StringBuilder sb = new StringBuilder();

        sb.append("SELECT ")
                .append(mc.getID())
                .append(',')
                .append(mc.getTableName())
                .append('.')
                .append(mc.getPrimaryKey()); // NOI18N
        sb.append(" FROM ")
                .append(mc.getTableName())
                .append(',')
                .append(SwmmPlusEtaWizardAction.TABLENAME_MONITOR_STATION);
        sb.append(" WHERE ")
                .append(mc.getTableName())
                .append('.')
                .append("station")
                .append(" = ")
                .append(SwmmInput.TABLENAME_MONITOR_STATION)
                .append(".id")
                .append(" AND ")
                .append(SwmmInput.TABLENAME_MONITOR_STATION)
                .append('.')
                .append(SwmmInput.FK_MONITOR_STATION_KEY)
                .append(" LIKE '")
                .append(sensor)
                .append('\'');

        if (LOG.isDebugEnabled()) {
            LOG.debug("executing SQL statement: \n" + sb);
        }

        final MetaObject[] metaObjects;

        try {
            metaObjects = SessionManager.getProxy().getMetaObjectByQuery(sb.toString(), 0);
        } catch (final ConnectionException ex) {
            throw new IOException("cannot get timeseries  objects from database: " + ex.getMessage(), ex);
        }
        if (LOG.isDebugEnabled()) {
            LOG.debug(metaObjects.length + " timeseries retrieved for station '" + sensor + "'");
        }
        return metaObjects;
    }

    /**
     * DOCUMENT ME!
     *
     * @param   sensor  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     *
     * @throws  IOException  DOCUMENT ME!
     */
    private TimeSeries loadEvents(final String sensor) throws IOException {
        LOG.info("loading events for '" + sensor + '\'');
        final MetaObject[] timeseriesMoList = getTimeseriesBeans(sensor);

        if (timeseriesMoList.length == 0) {
            throw new IOException("no timeseries found for '" + sensor
                        + "' (" + sensor + ")");
        }

        final TimeseriesRetriever retriever = TimeseriesRetriever.getInstance();
        final TimeseriesConverter converter = new LinzNetcdfConverter(true);
        final TimeSeries timeSeries;

        try {
            // we need only the first object
            final MetaObject timeseriesMo = timeseriesMoList[0];
            final CidsBean timeseriesBean = timeseriesMo.getBean();
            final String uri = (String)timeseriesBean.getProperty("uri"); // NOI18N
            if (LOG.isDebugEnabled()) {
                LOG.debug("loading remote timeseries for '" + timeseriesBean.getProperty("name") + "' from '"
                            + uri + "'");
            }

            final TimeseriesRetrieverConfig config = TimeseriesRetrieverConfig.fromUrl(uri);

            final Future<TimeSeries> result = retriever.retrieve(config, converter);
            timeSeries = result.get();
            if (LOG.isDebugEnabled()) {
                LOG.debug("remote timeseries for '" + timeseriesBean.getProperty("name")
                            + "' successully loaded");
            }
        } catch (Exception ex) {
            throw new IOException("could not load timeseries '" + sensor
                        + "' (" + sensor + "): " + ex.getLocalizedMessage(),
                ex);
        }

        final int timeseriesLength = timeSeries.getTimeStampsArray().length;
        if (LOG.isDebugEnabled()) {
            LOG.debug("event time series loaded with length of " + timeseriesLength);
        }

        return timeSeries;
    }

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private class EventDetectionTableModel extends AbstractTableModel {

        //~ Instance fields ----------------------------------------------------

        private final transient Logger LOG = Logger.getLogger(LinzSensorRenderer.EventDetectionTableModel.class);
        private final TimeSeries eventTimeseries;
        private final TimeStamp[] timeStamps;
        private final String[] columnNames;
        private final String[] columnKeys;
        private final Class[] columnClasses;

        //~ Constructors -------------------------------------------------------

        /**
         * Creates a new EtaConfigurationTableModel object.
         *
         * @param   eventTimeseries  etaConfigurations metaObjects DOCUMENT ME!
         *
         * @throws  IllegalStateException  DOCUMENT ME!
         */
        private EventDetectionTableModel(final TimeSeries eventTimeseries) {
            this.eventTimeseries = eventTimeseries;

            final Object valueKeyObject = eventTimeseries.getTSProperty(TimeSeries.VALUE_KEYS);
            if (valueKeyObject instanceof String[]) {
                final String[] valueKeys = (String[])valueKeyObject;
                this.columnNames = new String[valueKeys.length + 1];
                this.columnKeys = new String[valueKeys.length + 1];
                this.columnClasses = new Class[valueKeys.length + 1];
                if (LOG.isDebugEnabled()) {
                    LOG.debug(columnNames.length + " columns and " + valueKeys.length + " values");
                }

                this.columnNames[0] = org.openide.util.NbBundle.getMessage(
                        LinzSensorRenderer.class,
                        "LinzSensorRenderer.tblEventDetection.column.eventid");
                this.columnNames[1] = org.openide.util.NbBundle.getMessage(
                        LinzSensorRenderer.class,
                        "LinzSensorRenderer.tblEventDetection.column.startdate");
                this.columnNames[2] = org.openide.util.NbBundle.getMessage(
                        LinzSensorRenderer.class,
                        "LinzSensorRenderer.tblEventDetection.column.enddate");

                this.columnKeys[0] = valueKeys[1];
                this.columnKeys[1] = this.columnNames[1];
                this.columnKeys[2] = valueKeys[0];

                this.columnClasses[0] = String.class;
                this.columnClasses[1] = String.class;
                this.columnClasses[2] = String.class;

                int i = 0;
                for (final String valueKey : valueKeys) {
                    if (i >= 2) {
                        columnNames[i + 1] = valueKey;
                        columnKeys[i + 1] = valueKey;
                        columnClasses[i + 1] = Float.class;
                    }
                    i++;
                }
            } else {
                throw new IllegalStateException("unknown value key type: " + valueKeyObject); // NOI18N
            }

            // take the #st time series for the date column
            timeStamps = eventTimeseries.getTimeStampsArray();
        }

        //~ Methods ------------------------------------------------------------

        @Override
        public int getRowCount() {
            return timeStamps.length;
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public Object getValueAt(final int rowIndex, final int columnIndex) {
            if (columnIndex == 1) {
                // start date
                return this.timeStamps[rowIndex];
            } else {
                final Object o = eventTimeseries.getValue(
                        this.timeStamps[rowIndex],
                        this.columnKeys[columnIndex]);
                return o;
            }
        }

        @Override
        public void setValueAt(final Object value, final int row, final int col) {
            LOG.warn("operation setValueAt(...) not supported by " + this.getClass().getName());
        }

        @Override
        public String getColumnName(final int col) {
            return columnNames[col];
        }

        @Override
        public Class getColumnClass(final int col) {
            return columnClasses[col];
        }

        @Override
        public boolean isCellEditable(final int row, final int col) {
            return false;
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private class EventDetectionUpdater implements Runnable {

        //~ Instance fields ----------------------------------------------------

        private final transient Logger LOG = Logger.getLogger(LinzSensorRenderer.EventDetectionUpdater.class);
        private transient boolean run = true;
        private EventDetectionTableModel eventDetectionTableModel;
        private final String sensor;

        //~ Constructors -------------------------------------------------------

        /**
         * Creates a new EventDetectionUpdater object.
         *
         * @param  sensor  DOCUMENT ME!
         */
        public EventDetectionUpdater(final String sensor) {
            this.sensor = sensor;
        }

        //~ Methods ------------------------------------------------------------

        /**
         * DOCUMENT ME!
         */
        public void stopIt() {
            run = false;
            LOG.warn("EventDetectionUpdater stopped");
        }

        /**
         * DOCUMENT ME!
         *
         * @return  DOCUMENT ME!
         */
        public boolean isRunning() {
            return run;
        }

        @Override
        public void run() {
            if (run) {
                try {
                    if (LOG.isDebugEnabled()) {
                        LOG.debug("EventDetectionUpdater: loading events for sensor '" + sensor + "'");
                    }
                    final TimeSeries timeSeries = loadEvents(sensor);
                    exportAction.setTimeSeries(timeSeries);
                    eventDetectionTableModel = new EventDetectionTableModel(timeSeries);
                } catch (Exception e) {
                    LOG.error("EventDetectionUpdater: could not retrieve event detection values: " + e.getMessage(), e);
                    run = false;
                    EventQueue.invokeLater(new Runnable() {

                            @Override
                            public void run() {
                                progressBar.setIndeterminate(false);
                                org.openide.awt.Mnemonics.setLocalizedText(
                                    progressLabel,
                                    org.openide.util.NbBundle.getMessage(
                                        LinzSensorRenderer.class,
                                        "LinzSensorRenderer.progressLabel.error")); // NOI18N
                            }
                        });
                }

                if (run) {
                    EventQueue.invokeLater(new Runnable() {

                            @Override
                            public void run() {
                                if (LOG.isDebugEnabled()) {
                                    LOG.debug("EventDetectionUpdater: updating loaded results in GUI");
                                }
                                LinzSensorRenderer.this.tblEventDetection.setModel(eventDetectionTableModel);
                                ((CardLayout)cardPanel.getLayout()).show(cardPanel, "events");
                                exportButton.setEnabled(true);
                                run = false;
                            }
                        });
                } else {
                    LOG.warn("EventDetectionUpdater stopped, ignoring retrieved results");
                }
            }
        }
    }
}
